### PR TITLE
Fixes #12. Properly handle newline on Windows.

### LINKED ISSUE #12: problems formatting license headers on windows.
This plugin has been working fine for my development (MacOSX).
A colleague began using my project which is configured to use this plugin to format our sources. His development machine runs Windows7 64bit.
We checked out the project from SVN and when we ran SBT (0.13.7), the formatting of the licenses erased the file contents; afterwards, there is just the license header itself.

Has anyone experienced this peculiar behavior on windows?

### PR DESCRIPTION
**Pull request by aindlq**

### CODE REVIEW

**Comment by rubbish** [comment]
@aindlq Thanks for the patch. Merging.

**Comment by adamdecaf** [comment]
@rubbish did you release a new version with this fix?

**Comment by rubbish** [comment]
Done. 

> [info] banno/sbt-license-plugin@0.1.5 was released

**Comment by adamdecaf** [comment]
Sweet, thanks!

**Pull request merged**
